### PR TITLE
Optimizaciones y sintaxis tniASM

### PR DESCRIPTION
**Pull request by theNestruo**
Incluido Prueba_MSX
Corrección de versión en el comentario
Optimizaciones menores de código y de usabilidad (e.g.: búferes inicializados en el código del replayer)
Versión con sintaxis tniASM

### CODE REVIEW

**Comment by AugustoRuiz** [comment]
Hi!

Thank you very much for the changes! We should make the changes in all player versions (that is, MSX - RAM/ROM, ZX anc CPC). Can you do that?

**Comment by theNestruo** [comment]
Hi!

I can try doing the changes in all the player versions.
Unfortunately I don't have any toolchain for ZX or CPC; meaning that I won't be able to test them.
If you can test them, I can upload them to my branch.

**Comment by AugustoRuiz** [comment]
That would be great! Thank you!

**Comment by theNestruo** [comment]
Hi!
I've propagated the changes to CPC and ZX players. I'm quite confident about the ZX version, but not about the CPC version (it is too different to the other ones).
Please test the CPC and ZX players to ensure the changes are correct. Thank you!

Also please note that is no longer required to maintain two versions (ROM/RAM) for MSX; the same source is valid for both scenarios. The *_RAM file simply contains the variables and should be assembled in RAM, but the replayer routines can be assembled in ROM or in RAM.

**Comment by AugustoRuiz** [comment]
Thank you very much!

**Pull request merged**
